### PR TITLE
Pin trustwalletapp.com SSL certificate

### LINKED ISSUE #121: Setup SSL Pinning
For `trustwalletapp.com` domain

https://github.com/Moya/Moya/blob/master/docs/Providers.md

### PR DESCRIPTION
**Pull request by ghost**
Fix #121

### CODE REVIEW

**Comment by aleph7** [comment]
Didn't get a chance to test.

**Comment by michaelScoff** [comment]
Nice! Looks great, let me check something on our side, I think we need to use our certificate over cloudFlare one, but I need to set it up.

**Comment by michaelScoff** [comment]
@aleph7 I'm waiting for this to happen: https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html so we could pin all the subdomains as well

**Comment by michaelScoff** [comment]
Merging this, but I'm gonna disable it for now.

**Pull request merged**
