### PR TITLE
fix-tint

### PR DESCRIPTION
**Pull request by MillerApps**
Removed what appears to have been unneeded code which caused the issue mentioned in issue #290

### CODE REVIEW

**Comment by michaelScoff** [comment]
Did you check browser view?

**Comment by MillerApps** [comment]
The DApps browser? If so yes.
simulator screen shot - iphone 8 plus - 2018-02-08 at 23 06 16

**Comment by michaelScoff** [comment]
@MillerApps Remember now, do focus on textfield in the send view, it will show input toolbar, those buttons are broken.

**Comment by MillerApps** [comment]
Not sure what you mean they seem to be working for me. 
simulator screen shot - iphone 8 plus - 2018-02-08 at 23 10 08
simulator screen shot - iphone 8 plus - 2018-02-08 at 23 10 02

**Comment by michaelScoff** [comment]
@MillerApps That looks good! Hm, can’t remember then, I will double check tonight if that was it

**Comment by MillerApps** [comment]
It definitely seems like it was but, its always best to check on multiple devices. I'm off to bed now.

**Pull request merged**
