### PR TITLE
remove redundant method

### PR DESCRIPTION
**Pull request by darlhz**
This method is not being used anywhere. A possible leftover from previous refactoring?

### CODE REVIEW

**Comment by vikmeup** [comment]
@darlhz Do you have a script to run and see all unused variables and methods? Xcode not doing a great job on this

**Comment by darlhz** [comment]
@vikmeup the method name was changed to this one in a81afedfa36431352e3391d988b546633cf247a7
`func tickers(with tokenPrices: [TokenPrice]) -> Promise<[CoinTicker]> `
No, I was just studying the code. I was also curious if there's any script can check that :)

**Comment by vikmeup** [comment]
@darlhz I will on check on this, I had 4 days long refactor 😄  trying to make tests happy

**Comment by vikmeup** [comment]
@darlhz this methods has been used by `TokensViewModel`

**Comment by vikmeup** [comment]
@darlhz you are right! merged that in

**Pull request merged**
